name: Write comment to issue

on:
  workflow_call:
    inputs:
      issue_comment:
        required: true
        type: string
      issue_number:
        required: true
        type: number
    secrets:
      tempToken:
        required: true

jobs:
  create-comment:
    runs-on: ubuntu-latest
    steps:
    - name: Add comment to issue
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.tempToken }}
        script: |
          const issueComment = context.payload.issue.number;
          github.rest.issues.createComment({
            issue_number: ${{inputs.issue_number}},
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: ${{ inputs.issue_comment }}
          });
