name: Create Repository Workflow

on:
  workflow_call:
    inputs:
      repo-name:
        required: true
        type: string
    secrets:
      TEMP_TOKEN:
        required: true

jobs:
  create-repository:
    runs-on: ubuntu-latest
    steps:
    
    - name: Create a New Repository
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.TEMP_TOKEN }}
        script: |
          const repoName = ${{ inputs.repo-name }};
          // Logic to create a new repository
          octokit.rest.repos.createForAuthenticatedUser({
            repoName,
          });
